language: c

matrix:
  include:
    - os: windows
      script:
        - mkdir build && cd build
        - cmake -A Win32 ..
        - cmake --build . --config Release
        - cd Release
        - for f in *dll; do mv "$f" "lib$f"; done;
        - 7z a -tzip "${TRAVIS_REPO_SLUG#*/}-windows-x86-$TRAVIS_TAG.zip" *.dll ../../src/*.lua
    - os: windows
      script:
        - mkdir build && cd build
        - cmake -A x64 ..
        - cmake --build . --config Release
        - cd Release
        - for f in *dll; do mv "$f" "lib$f"; done;
        - 7z a -tzip "${TRAVIS_REPO_SLUG#*/}-windows-x64-$TRAVIS_TAG.zip" *.dll ../../src/*.lua
    - dist: trusty
    - os: osx
      osx_image: xcode6.4

script:
  - mkdir build && cd build
  - cmake ..
  - cmake --build .
  - zip -j "${TRAVIS_REPO_SLUG#*/}-$TRAVIS_OS_NAME-x64-$TRAVIS_TAG.zip" ?(*.so|*.dylib) ../src/*.lua

deploy:
  provider: releases
  skip_cleanup: true
  on:
    tags: true
    branch: master
  file_glob: true
  file: "${TRAVIS_REPO_SLUG#*/}*.zip"
  api_key:
    secure: pVQ2yHVbJqjWa1H+UoJeK4UOosdhEFaQX94J2SPajpCtrpGmzUqhAHLCS7K9oJSxIjTw8PHynJhK7fTXdO3xubUvK4FTMubZK1lJIVrHNU2wjjvZDra8cpYVWJ1Yg3bS+8ITAQki8+tBrv/rKxe68uabgKgG4/twLx9t/ILk/1Q9KSjiXV7yNJfeQUeLEVad+YRLY+VJ1c/2eDdA0ujbqs+SIcB68sNjS7cgP5jTkFb/V2+FAIEsxerFGHHR5Bje6wA0st23G71/cWAcX5ICVGfZmT/7UztyQWrWzYQkR23WfQbJjof5iehSRkeEJixzodDw2p2JsQ21i+otgws0W7ky2UbaFTMYNxmJcm9YpUWQmfdo7O/Whr7IP8yb0/Q5qK6RYb/dOaN/DEB5IvFXSj+H7mZHrdaAN8oCy+iMwTYqVn2gMh/XE1hO2uRzP5xQAvKeehQXHx5oN02Td9LVh0EQ5x0txDGBUxPiIR67Z/oSripUmKNUOVKc8hpCJTWOxWtLftIWkQmbG4sQQa1XpiktzNNUiEEdpGlNBmAOxCTVhtAkODnOQDEhoKDqpjMHFAp9VV9L6KhC1/di/AaMXc4tLhARYTXLSD+yrZpDsBUnKiXmDLo+yS/H/3lV2QBKX5cbRT0IzfigYQg6V0CHpwKNuZ0+0lfLLNnBdn8D+PU=